### ISSUE TITLE
Issues on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by deependdesigns** [WebRTSP/ReStreamer#31] opened 2022-12-27 03:46 UTC
Everything appeared to install successfully, however when I launch the stream in the browser and monitor I get the following:

```
2022-12-26T21:35:41-06:00 rtsp-to-webrtsp.ReStreamer[3659]: ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
2022-12-26T21:35:41-06:00 rtsp-to-webrtsp.ReStreamer[3659]: [2022-12-26 21:35:41.841] [ReStreamer] [info] Config "/snap/rtsp-to-webrtsp/360/etc/restreamer.conf" not found
2022-12-26T21:35:41-06:00 rtsp-to-webrtsp.ReStreamer[3659]: [2022-12-26 21:35:41.841] [ReStreamer] [info] Loading config "/var/snap/rtsp-to-webrtsp/common/restreamer.conf"
2022-12-26T21:35:41-06:00 -[3659]: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
2022-12-26T21:35:41-06:00 rtsp-to-webrtsp.ReStreamer[3659]: 0:00:00.059972112  3659   0xfa3a40 WARN      GST_PLUGIN_LOADING gstplugin.c:792:_priv_gst_plugin_load_file_for_registry: module_open failed: libpulsecommon-13.99.so: cannot open shared object file: No such file or directory
2022-12-26T21:35:41-06:00 -[3659]: Failed to load plugin '/snap/rtsp-to-webrtsp/360/usr/lib/arm-linux-gnueabihf/gstreamer-1.0/libgstfluidsynthmidi.so': libpulsecommon-13.99.so: cannot open shared object file: No such file or directory
2022-12-26T21:35:41-06:00 rtsp-to-webrtsp.ReStreamer[3659]: 0:00:00.068908812  3659   0xfa3a40 WARN      GST_PLUGIN_LOADING gstplugin.c:792:_priv_gst_plugin_load_file_for_registry: module_open failed: libpulsecommon-13.99.so: cannot open shared object file: No such file or directory
2022-12-26T21:35:41-06:00 -[3659]: Failed to load plugin '/snap/rtsp-to-webrtsp/360/usr/lib/arm-linux-gnueabihf/gstreamer-1.0/libgstfluidsynthmidi.so': libpulsecommon-13.99.so: cannot open shared object file: No such file or directory
2022-12-26T21:35:41-06:00 rtsp-to-webrtsp.ReStreamer[3659]: [2022-12-26 21:35:41.917] [HttpServer] [info] Starting HTTP server on port 5080
2022-12-26T21:35:41-06:00 rtsp-to-webrtsp.ReStreamer[3659]: [2022-12-26 21:35:41.918] [WsServer] [info] Starting WS server on port 5554
```

**Comment by RSATom** [comment] 2022-12-27 03:57
@deependdesigns I don't see anything critical. It's just some noise from snap and GStreamer.
Are you able to see video in your browser? If yes, then nothing to care about...

**Comment by RSATom** [comment] 2022-12-27 04:13
> 2022-12-26T21:35:41-06:00 -[3659]: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.

This should be fixed now

**Comment by deependdesigns** [comment] 2022-12-27 04:24
That was with the default configuration and am unable to view the stream. I
get a grey background with a loading animation over where the feed should
be.  When I include my rtsp in the configuration and replace the streamers
I get the following in the log monitor:

2022-12-26T22:23:07-06:00 -[4004]: unknown transport field "timeout=60"
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:25.112546637  4004 0x6fe21118 WARN                    faad
gstfaad.c:268:gst_faad_set_format:<faad11> buggy faad version, wrong nr of
channels 2 instead of 1
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:25.117088239  4004 0x6fe21118 WARN            uridecodebin
gsturidecodebin.c:920:unknown_type_cb:<uridecodebin11> warning: No decoder
available for type 'audio/x-raw, format=(string)S16LE,
layout=(string)interleaved, rate=(int)8000, channels=(int)2,
channel-mask=(bitmask)0x0000000000000003'.
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:25.117404533  4004 0x6fe21118 WARN               decodebin
gstdecodebin2.c:4678:gst_decode_bin_expose:<decodebin23> error: no suitable
plugins found:
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]: Missing
decoder: Raw 16-bit PCM audio (audio/x-raw, format=(string)S16LE,
layout=(string)interleaved, rate=(int)8000, channels=(int)2,
channel-mask=(bitmask)0x0000000000000003)
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:25.150844243  4004 0x6fe210e0 WARN                 default
libde265-dec.c:581:gst_libde265_dec_set_format:<libde265dec11> warning:
Unsupported extra data version 1, decoding may fail
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:25.170716647  4004 0x6fe210e0 WARN            uridecodebin
gsturidecodebin.c:920:unknown_type_cb:<uridecodebin11> warning: No decoder
available for type 'video/x-raw, format=(string)I420, width=(int)2304,
height=(int)1296, interlace-mode=(string)progressive,
multiview-mode=(string)mono,
multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono,
pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2,
colorimetry=(string)bt709, framerate=(fraction)15/1'.
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:25.171152573  4004 0x6fe210e0 WARN               decodebin
gstdecodebin2.c:4678:gst_decode_bin_expose:<decodebin22> error: no suitable
plugins found:
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]: Missing
decoder: Uncompressed planar YUV 4:4:4 (video/x-raw, format=(string)I420,
width=(int)2304, height=(int)1296, interlace-mode=(string)progressive,
multiview-mode=(string)mono,
multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono,
pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2,
colorimetry=(string)bt709, framerate=(fraction)15/1)
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:25.171302517  4004 0x6fe210e0 WARN            uridecodebin
gsturidecodebin.c:987:no_more_pads_full:<uridecodebin11> error: no suitable
plugins found:
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
gstdecodebin2.c(4678): gst_decode_bin_expose ():
/GstPipeline:pipeline11/GstURIDecodeBin:uridecodebin11/GstDecodeBin:decodebin22:
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]: no suitable
plugins found:
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]: Missing
decoder: Uncompressed planar YUV 4:4:4 (video/x-raw, format=(string)I420,
width=(int)2304, height=(int)1296, interlace-mode=(string)progressive,
multiview-mode=(string)mono,
multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono,
pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2,
colorimetry=(string)bt709, framerate=(fraction)15/1)
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
gstdecodebin2.c(4678): gst_decode_bin_expose ():
/GstPipeline:pipeline11/GstURIDecodeBin:uridecodebin11/GstDecodeBin:decodebin23:
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]: no suitable
plugins found:
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]: Missing
decoder: Raw 16-bit PCM audio (audio/x-raw, format=(string)S16LE,
layout=(string)interleaved, rate=(int)8000, channels=(int)2,
channel-mask=(bitmask)0x0000000000000003)
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:25.173697768  4004 0x6fe210e0 ERROR                default
libde265-dec.c:521:_gst_libde265_image_available:<libde265dec11> Failed to
negotiate format
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:25.173759069  4004 0x6fe210e0 ERROR                default
libde265-dec.c:274:gst_libde265_dec_get_buffer:<libde265dec11> Failed to
notify about available image
2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:25.442951917  4004 0x6fe210e0 WARN                 default
libde265-dec.c:859:gst_libde265_dec_handle_frame:<libde265dec11> warning:
Cannot run decoder multi-threaded because stream does not support WPP
(code=1000)
2022-12-26T22:23:13-06:00 rtsp-to-webrtsp.ReStreamer[4004]: [2022-12-26
22:23:13.323] [WsServer] [info] Got DESCRIBE request for "CNC%20Cam"
2022-12-26T22:23:13-06:00 -[4004]: unknown transport field "timeout=60"
2022-12-26T22:23:13-06:00 -[4004]: unknown transport field "timeout=60"
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:31.314068768  4004 0x6fe21368 WARN                    faad
gstfaad.c:268:gst_faad_set_format:<faad12> buggy faad version, wrong nr of
channels 2 instead of 1
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:31.319918410  4004 0x6fe21368 WARN            uridecodebin
gsturidecodebin.c:920:unknown_type_cb:<uridecodebin12> warning: No decoder
available for type 'audio/x-raw, format=(string)S16LE,
layout=(string)interleaved, rate=(int)8000, channels=(int)2,
channel-mask=(bitmask)0x0000000000000003'.
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:31.320590841  4004 0x6fe21368 WARN               decodebin
gstdecodebin2.c:4678:gst_decode_bin_expose:<decodebin25> error: no suitable
plugins found:
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]: Missing
decoder: Raw 16-bit PCM audio (audio/x-raw, format=(string)S16LE,
layout=(string)interleaved, rate=(int)8000, channels=(int)2,
channel-mask=(bitmask)0x0000000000000003)
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:31.328079191  4004 0x6fe21330 WARN                 default
libde265-dec.c:581:gst_libde265_dec_set_format:<libde265dec12> warning:
Unsupported extra data version 1, decoding may fail
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:31.355499478  4004 0x6fe21330 WARN            uridecodebin
gsturidecodebin.c:920:unknown_type_cb:<uridecodebin12> warning: No decoder
available for type 'video/x-raw, format=(string)I420, width=(int)2304,
height=(int)1296, interlace-mode=(string)progressive,
multiview-mode=(string)mono,
multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono,
pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2,
colorimetry=(string)bt709, framerate=(fraction)15/1'.
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:31.355892541  4004 0x6fe21330 WARN               decodebin
gstdecodebin2.c:4678:gst_decode_bin_expose:<decodebin24> error: no suitable
plugins found:
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]: Missing
decoder: Uncompressed planar YUV 4:4:4 (video/x-raw, format=(string)I420,
width=(int)2304, height=(int)1296, interlace-mode=(string)progressive,
multiview-mode=(string)mono,
multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono,
pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2,
colorimetry=(string)bt709, framerate=(fraction)15/1)
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:31.356104098  4004 0x6fe21330 WARN            uridecodebin
gsturidecodebin.c:987:no_more_pads_full:<uridecodebin12> error: no suitable
plugins found:
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
gstdecodebin2.c(4678): gst_decode_bin_expose ():
/GstPipeline:pipeline12/GstURIDecodeBin:uridecodebin12/GstDecodeBin:decodebin24:
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]: no suitable
plugins found:
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]: Missing
decoder: Uncompressed planar YUV 4:4:4 (video/x-raw, format=(string)I420,
width=(int)2304, height=(int)1296, interlace-mode=(string)progressive,
multiview-mode=(string)mono,
multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono,
pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2,
colorimetry=(string)bt709, framerate=(fraction)15/1)
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
gstdecodebin2.c(4678): gst_decode_bin_expose ():
/GstPipeline:pipeline12/GstURIDecodeBin:uridecodebin12/GstDecodeBin:decodebin25:
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]: no suitable
plugins found:
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]: Missing
decoder: Raw 16-bit PCM audio (audio/x-raw, format=(string)S16LE,
layout=(string)interleaved, rate=(int)8000, channels=(int)2,
channel-mask=(bitmask)0x0000000000000003)
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:31.599739892  4004 0x6fe21330 WARN                 default
libde265-dec.c:859:gst_libde265_dec_handle_frame:<libde265dec12> warning:
Cannot run decoder multi-threaded because stream does not support WPP
(code=1000)
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:31.610965178  4004 0x72604f98 WARN                 rtspsrc
gstrtspsrc.c:6326:gst_rtsp_src_receive_response:<source> receive interrupted
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:31.611013666  4004 0x72604f98 WARN                 rtspsrc
gstrtspsrc.c:6424:gst_rtspsrc_try_send:<source> receive interrupted
2022-12-26T22:23:15-06:00 rtsp-to-webrtsp.ReStreamer[4004]:
0:01:31.611041895  4004 0x72604f98 WARN                 rtspsrc
gstrtspsrc.c:8672:gst_rtspsrc_pause:<source> PAUSE interrupted
2022-12-26T22:23:19-06:00 rtsp-to-webrtsp.ReStreamer[4004]: [2022-12-26
22:23:19.261] [WsServer] [info] Got DESCRIBE request for "CNC%20Cam"
2022-12-26T22:23:19-06:00 -[4004]: unknown transport field "timeout=60"
2022-12-26T22:23:19-06:00 -[4004]: unknown transport field "timeout=60"

**Comment by RSATom** [comment] 2022-12-27 04:29
@deependdesigns can you please clarify what video codec your cam uses?

**Comment by EmpireofKings** [comment] 2022-12-27 05:40
> @deependdesigns can you please clarify what video codec your cam uses?

It looks like they are receiving H265, which would be why they don't see any stream in the browser. 

> 2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]: 0:01:25.173759069 4004 0x6fe210e0 ERROR default libde265-dec.c:274:gst_libde265_dec_get_buffer:<libde265dec11> Failed to notify about available image 2022-12-26T22:23:09-06:00 rtsp-to-webrtsp.ReStreamer[4004]: 0:01:25.442951917 4004 0x6fe210e0 WARN default libde265-dec.c:859:gst_libde265_dec_handle_frame:<libde265dec11> warning: Cannot run decoder multi-threaded because stream does not support WPP

**Comment by deependdesigns** [comment] 2022-12-27 05:41
Is there anything I can do?

**Comment by EmpireofKings** [comment] 2022-12-27 05:42
@deependdesigns go to your camera's webpage and change the encoding format from h265 to h264.

**Comment by RSATom** [comment] 2022-12-27 05:43
Yes, it's highly possible h265. But current ReStreamer implementation supports only h264 codec. @deependdesigns you can try change codec in your cam settings.

**Comment by RSATom** [comment] 2022-12-27 05:44
It's also possible `ReStreamer` is just broken on RPi. I didn't try the latest version myself on RPi yet...

**Comment by deependdesigns** [comment] 2022-12-27 05:56
Dang, ok. I'm trying to find a solution to stream my IP camera on my CNC to
CNCJS but I keep hitting road blocks.

**Comment by RSATom** [comment] 2022-12-27 05:57
@deependdesigns I'll try it today on RPi.

**Comment by RSATom** [comment] 2022-12-27 05:59
@deependdesigns also, can you please share what exactly IP Cam you are trying to use?

**Comment by deependdesigns** [comment] 2022-12-27 06:00
I really appreciate it

**Comment by deependdesigns** [comment] 2022-12-27 06:02
https://a.co/d/9YlMj8e

**Comment by RSATom** [comment] 2022-12-27 06:15
Hm... According to [user manual](https://www.wansview.com/uploadfiles/2022/08/20220831184323966.pdf) this cam supports h264. Did you use rtsp url to get access to it?

**Comment by deependdesigns** [comment] 2022-12-27 06:29
I did use rtsp URL. Is there a parameter I can pass in on the URL? I didn't
see any encoding options within the app.

**Comment by RSATom** [comment] 2022-12-27 06:31
Hm... Now I think it's something wrong inside `ReStreamer`...
Did you try to open that rtsp with some media player?

**Comment by deependdesigns** [comment] 2022-12-27 06:37
I was actually able to get it working using cvnc earlier, but the latency
was horrible. I saw someone else mention your software as a lower latency
option. I can also stream on my windows machine using VNC but couldn't
figure out how to restream it. On windows the latency was almost
negligeable.

**Comment by RSATom** [comment] 2022-12-27 06:42
yes, it should give minimal latency since doesn't do any transcoding... And it's important for me to get it working for you, or at least find the reason why it can't... Please try open rtsp with VLC and look what codec it shows.

On my side, I'll try to install it on my RPi. Btw, what snap channel did you use? `stable` or `edge`?

**Comment by deependdesigns** [comment] 2022-12-27 06:46
I started on edge but reverted back to stable.

I hate to do this, but I will have to try with VNC tomorrow morning. It's
almost 1am and I'm exhausted.

**Comment by deependdesigns** [comment] 2022-12-27 06:47
Sorry, VLC

**Comment by RSATom** [comment] 2022-12-27 06:52
Ok, np. meantime I'll try RPi myself.

**Comment by EmpireofKings** [comment] 2022-12-27 06:53
> Is there anything I can do?

If you have a monitor attached to the raspberry pi, can you try this command from the command line ? 

`gst-launch-1.0 -v playbin uri="rtsp://your-camera-ip-address:your-rtsp-port/your-endpoint"`

**Comment by RSATom** [comment] 2022-12-27 06:55
snap package is self contained, so it doesn't matter if GStreamer is working (or even present) on host.

**Comment by deependdesigns** [comment] 2022-12-27 06:57
Just remembered I have VNC on my phone. Hopefully my attachment comes
through.

**Comment by RSATom** [comment] 2022-12-27 16:11
@deependdesigns I've tried both stable and edge version of snap on my Raspberry Pi 2 Model B and everything looks working...
So please post info from VLC about your rtsp when you have a chance...

**Comment by deependdesigns** [comment] 2022-12-27 19:08
I just realized that my attachment didn't come through. I was replying through email.  I get the following from VLC:

Video
Codec MPEG-H Part2/HEVC (H.265)
Resolution 2304x1296
Framerate 15

Audio
Codec MPEG AAC Audio
Channels 1
Sample rate 8000 Hz

**Comment by EmpireofKings** [comment] 2022-12-27 20:03
> I just realized that my attachment didn't come through. I was replying through email. I get the following from VLC:
> 
> Video Codec MPEG-H Part2/HEVC (H.265) Resolution 2304x1296 Framerate 15
> 
> Audio Codec MPEG AAC Audio Channels 1 Sample rate 8000 Hz

Yup, the problem is that your camera is streaming with H265 ... The project is currently limited to H264/VP8. 

You need to find out how to change the encoder settings on your camera to H264, if you can't do it from the camera webpage, you can try doing it with an onvif client.

**Comment by deependdesigns** [comment] 2022-12-27 20:06
I'll try that when I get home. I do see ONVIF as an option.

**Comment by EmpireofKings** [comment] 2022-12-27 20:10
> I'll try that when I get home. I do see ONVIF as an option.

If onvif doesn't work, make sure that the camera has the latest firmware downloaded. It looks like they just recently added onvif support to that camera.

**Comment by deependdesigns** [comment] 2022-12-28 03:02
I've got good news and bad news.

Good:

I was able to change the RTSP source to ch1 and am now able to see the stream in the browser using WebRTSP/Restreamer

Bad:

I put the same URL that gives me the stream in the browser into CNCJS and I get a black screen.  I did notice that http://192.168.1.130:5080/ (the path to WebRTSP/Restreamer) looks like the stream is embeded within HTML.  Am I missing something? I apologize, I don't have much experience in RTSP

**Comment by RSATom** [comment] 2022-12-28 04:09
@deependdesigns Can you please elaborate a little bit what CNCJS is and what exactly you trying to achieve with it?

**Comment by RSATom** [comment] 2022-12-28 04:12
I think I've found what CNCJS is: https://cnc.js.org/

But I can't understand how (and why) you are trying to embed ReStreamer's URL there. :thinking:

**Comment by deependdesigns** [comment] 2022-12-28 04:14
Absolutely.

CNCJS is a web-based interface for CNC milling controllers running Grbl.
Essentially it lets me operate my CNC Milling Machine from my computer or
phone.  It also has the ability to embed a webcam or MJPG stream within the
interface for job monitoring. I'm trying to figure out how to get the IP
Cam's stream into the CNCJS web interface.

https://cnc.js.org/docs/faq/#restream-rtsp-to-m-jpeg

**Comment by RSATom** [comment] 2022-12-28 04:24
I think there is some misunderstanding... It looks like CNCJS expects Motion JPEG source (i.e. it just gets jpeg with some interval from provided URL and show it in UI) - please correct me if I'm wrong. But ReStreamer produces WebRTC video.

So to solve you task you can try to do video transcoding (from h264 or h265 to MJPEG) with ffmpeg for example. But it's heavy operation, and I don't know if your RPi has enough power for that.

Other option - check if your IP Cam can provide Motion JPEG output.

**Comment by deependdesigns** [comment] 2022-12-28 04:31
Ah, it seems I've been barking up the wrong tree.  I'll try to get ffmpeg
with ffserver running again and see what I can figure out.

**Comment by deependdesigns** [comment] 2022-12-28 04:32
Thanks again for your help

**Comment by RSATom** [comment] 2023-02-10 09:28
Since it was not revisited for a long time, I treat it as not issue anymore... Please reopen if you still need some assistance.

**Closed by RSATom** 2023-02-10 09:28 UTC
